apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: exoln-lex

namespace: exoln-lex

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: exoln-lex
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize

images:
  - name: exoln-lex
    newName: ghcr.io/exolnhubs/exoln-lex
    newTag: latest
