apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: exoln-lex-pdb
  namespace: exoln-lex
  labels:
    app.kubernetes.io/name: exoln-lex
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: exoln-lex
      app.kubernetes.io/component: api
